global:
  config_version: 3
input:
  type: file
  path: /var/log/syslog
  readall: false
imports:
- type: grok_patterns
  dir: ./patterns 
metrics:
- type: counter
  name: orchestrator_relayer_error_count
  help: orchestrator relayer total errors 
  match: '%{SYSLOGTIMESTAMP} %{HOSTNAME:instance} gbt\[%{DATA}\]: \[%{TIMESTAMP_ISO8601} ERROR %{DATA:app}::%{DATA:job} %{GREEDYDATA:error}'
  labels:
    error_message: '{{.error}}'
    logfile: '{{base .logfile}}'
server:
  protocol: http
  port: 9144
